sudo: required
dist: trusty
language: node_js

services:
  - docker
  #- mysql

node_js:
  - "6.10.2"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8

before_install:
  - sudo /etc/init.d/mysql stop
  - docker pull mysql:5.7
  - docker build -t sw/mysql ./docker/mysql
  - docker run --name sql -d -p 3306:3306  sw/mysql

script:
  - npm run migrate
  - npm run ci:travis
